#!/usr/bin/env node
/**
 * Copies the version from package.json into every other place that records it.
 *
 *   node scripts/sync-version.mjs            write the files
 *   node scripts/sync-version.mjs --check    report drift, write nothing
 *
 * Why this exists: the version is recorded in three places, but only one of
 * them needs writing by hand.
 *
 *   package.json                 the single source, bumped by `npm version`
 *   src-tauri/tauri.conf.json    what Tauri reads for the app version
 *   app/tauri.properties         Android's versionName / versionCode
 *
 * The third is *autogenerated* - it carries a "DO NOT EDIT" banner and Tauri
 * rewrites it from tauri.conf.json on every build, deriving versionCode from the
 * version string. So this script does not touch Gradle at all, which is worth
 * stating because the obvious approach (and what Otter Music does, being a
 * Capacitor app with no such plugin) is to rewrite build.gradle by hand.
 *
 * `src-tauri/Cargo.toml` also has a `version`, and it is deliberately left
 * alone: Tauri takes the app version from tauri.conf.json, and bumping the crate
 * version would invalidate the whole Rust build cache on every release for no
 * effect.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TAURI_CONF = join(ROOT, 'src-tauri/tauri.conf.json');

/** The substitutions to apply, as [pattern, replacement, label] triples. */
export function planEdits({ version, tauriConf }) {
  const pattern = /("version"\s*:\s*)"[^"]*"/;
  if (!pattern.test(tauriConf)) {
    throw new Error('tauri.conf.json has no "version" field to update');
  }
  return [
    {
      label: 'tauri.conf.json version',
      before: tauriConf,
      after: tauriConf.replace(pattern, '$1"' + version + '"'),
    },
  ];
}

function main() {
  const checkOnly = process.argv.includes('--check');

  const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
  if (!version) throw new Error('package.json has no version');

  const edits = planEdits({ version, tauriConf: readFileSync(TAURI_CONF, 'utf8') });

  let drifted = false;
  for (const edit of edits) {
    const changed = edit.before !== edit.after;
    drifted ||= changed;
    if (checkOnly) {
      console.log((changed ? 'DRIFT  ' : 'ok     ') + edit.label);
      continue;
    }
    if (changed) {
      writeFileSync(TAURI_CONF, edit.after, 'utf8');
      console.log('updated ' + edit.label);
    } else {
      console.log('unchanged ' + edit.label);
    }
  }

  // versionCode is deliberately not printed: Tauri derives it from the version
  // in its own scheme (0.3.0 -> 3000), so anything computed here would be a
  // number that does not match the shipped APK.
  console.log('\nversion ' + version + ' (Tauri derives the Android versionCode)');

  if (checkOnly && drifted) {
    console.error('\nVersion numbers are out of sync. Run: node scripts/sync-version.mjs');
    process.exit(1);
  }
}

// Only run when executed, so the tests can import the pure helpers.
// URL compared against URL: `fileURLToPath(import.meta.url)` is a Windows path
// and `pathToFileURL(...).href` is a URL, so comparing those two never matches
// and the script silently does nothing.
if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  main();
}
